apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medrag
  labels:
    app.kubernetes.io/name: medrag
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app.kubernetes.io/name: medrag
    app.kubernetes.io/instance: {{ .Release.Name }}
